jets:
  inputs:
    - pt_btagJes
    - eta_btagJes
  labels:
    - HadronConeExclTruthLabelID
    - HadronConeExclExtendedTruthLabelID
    - HadronConeExclTruthLabelPt
    - HadronConeExclTruthLabelLxy
    - HadronConeExclTruthLabelDR
    - pt
    - eta
    - mass
    - n_tracks
    - eventNumber

tracks:
  inputs:
    - d0
    - z0SinTheta
    - dphi
    - deta
    - qOverP
    - lifetimeSignedD0Significance
    - lifetimeSignedZ0SinThetaSignificance
    - phiUncertainty
    - thetaUncertainty
    - qOverPUncertainty
    - numberOfPixelHits
    - numberOfSCTHits
    - numberOfInnermostPixelLayerHits
    - numberOfNextToInnermostPixelLayerHits
    - numberOfInnermostPixelLayerSharedHits
    - numberOfInnermostPixelLayerSplitHits
    - numberOfPixelSharedHits
    - numberOfPixelSplitHits
    - numberOfSCTSharedHits
    - leptonID
  labels:
    - ftagTruthOriginLabel
    - ftagTruthTypeLabel
    - ftagTruthVertexIndex

#flow:
#  inputs:
#    - pt
#    - energy
#    - deta
#    - dphi
