variables: !include xbb-variables.yaml

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

hbb: &hbb
  name: hbb
  pattern: user.jabarr.801471.e8441_e7400_s3681_r13144_r13146_p5488.tdd.*h5/*.h5
hcc: &hcc
  name: hcc
  pattern: user.jabarr.801472.e8441_e7400_s3681_r13144_r13146_p5488.tdd.flow.*/*.h5
top: &top
  name: top
  pattern: user.jabarr.426345*/*.h5
    # - user.jabarr.426345.e6880_s3681_r13144_p5488.tdd.flow.*/*.h5
    # - user.jabarr.426345.e6880_s3681_r13145_p5488.tdd.flow.*/*.h5
qcd: &qcd
  name: qcd
  pattern: user.jabarr.36470*/*.h5
    # - user.jabarr.364703.e7142_s3681_r13144_p5488.tdd.flow.*/*.h5
    # - user.jabarr.364704.e7142_s3681_r13144_p5488.tdd.flow.*/*.h5
    # - user.jabarr.364705.e7142_s3681_r13144_p5488.tdd.flow.*/*.h5

inclusive: &inclusive
  name: inclusive
  cuts: []

components:
  - region:
      <<: *inclusive
    sample:
      <<: *hbb
    flavours: [hbb]
    num_jets: 14_500_000

  - region:
      <<: *inclusive
    sample:
      <<: *hcc
    flavours: [hcc]
    num_jets: 14_500_000

  - region:
      <<: *inclusive
    sample:
      <<: *top
    flavours: [top]
    num_jets: 8_000_000

  - region:
      <<: *inclusive
    sample:
      <<: *qcd
    flavours: [qcd]
    num_jets: 22_000_000

resampling:
  target: hbb
  method: countup
  sampling_fraction: 1
  variables:
    pt:
      bins: [[250_000, 1_300_000, 50]]
    abs_eta:
      bins: [[0, 2, 20]]
    mass:
      bins: [[50_000, 300_000, 50]]

global:
  batch_size: 4_000_000
  num_jets_estimate: 10_000_000
  base_dir: /share/lustre/jbarr/flow/
  merge_test_samples: True
