variables: !include xbb-variables.yaml

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

hbb: &hbb
  name: hbb # covers 514722 - 514741
  pattern: vhbb/mc*.h5

hcc: &hcc
  name: hcc
  pattern: vhcc/mc*.h5

top: &top
  name: top
  pattern: top/mc*.h5
qcd: &qcd
  name: qcd
  equal_jets: True
  pattern:
        - jz/mc20_jz3.h5
        - jz/mc20_jz4.h5
        - jz/mc20_jz5.h5
        - jz/mc23_jz3.h5
        - jz/mc23_jz4.h5
        - jz/mc23_jz5.h5

inclusive: &inclusive
  name: inclusive
  cuts: 
    - ["mass", ">", 50_000]

components:
  - region:
      <<: *inclusive
    sample:
      <<: *hbb
    flavours: [hbb]
    num_jets: 25_000_000

  - region:
      <<: *inclusive
    sample:
      <<: *hcc
    flavours: [hcc]
    num_jets: 25_000_000

  - region:
      <<: *inclusive
    sample:
      <<: *top
    flavours: [top]
    num_jets: 15_000_000 #10_400_000

  - region:
      <<: *inclusive
    sample:
      <<: *qcd
    flavours: [qcd]
    num_jets: 30_000_000
    equal_jets: True

resampling:
  target: hbb
  method: countup
  sampling_fraction: auto
  variables:
    pt:
      bins: [[250_000, 1_300_000, 50]]
    abs_eta:
      bins: [[0, 2, 20]]
    mass:
      bins: [[50_000, 300_000, 40]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  batch_size: 1_000_000 #4_000_000
  num_jets_estimate: 15_000_000 #1_100_000 #10_00_000
  ntuple_dir: /share/rcifdata/jbarr/mc23-GN2X-Training/ntuples
  base_dir: /share/rcifdata/jbarr/mc23-GN2X-Training
  merge_test_samples: True
