# k-folded split - fold 2 out of 4
train:
  - [jetFoldHash, "%4!=", 2] # uncomment to run fold 2
  - [eventNumber, "%10<=", 8]
val:
  - [jetFoldHash, "%4!=", 2] # uncomment to run fold 2
  - [eventNumber, "%10==", 9]
test:
  - [jetFoldHash, "%4==", 2] # uncomment to run fold 2
